package com.investment.pricingengine.domain.port.in;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Inbound port — called by the Kafka consumer when a MarketPriceUpdated event arrives.
 */
public interface ProcessMarketPriceUseCase {

    /**
     * @param correlationId propagated from the original event for distributed tracing
     * @param symbol        ticker symbol (e.g. "AAPL")
     * @param price         new market price
     * @param timestamp     time the price was generated by the market data source
     */
    void process(String correlationId, String symbol, BigDecimal price, Instant timestamp);
}
